"""Zero-Dependency Interactive HTML Governance Dashboard Generator."""

from __future__ import annotations

import json
from .dimensions import QualityScorecard
from .pii_detector import PIIScanResult


class DashboardExporter:
    """Exports self-contained executive HTML dashboards with zero external CDN dependencies."""

    @classmethod
    def generate_html(
        cls,
        scorecard: QualityScorecard,
        pii: PIIScanResult,
    ) -> str:
        score = scorecard.overall_score
        status_color = "#10b981" if score >= 90 else ("#f59e0b" if score >= 75 else "#ef4444")
        status_label = "EXCELLENT" if score >= 90 else ("ACCEPTABLE" if score >= 75 else "CRITICAL")

        # Prepare dimension bars
        dim_rows_html = []
        for name, dim in scorecard.dimension_scores.items():
            color = "#10b981" if dim.status == "PASS" else ("#f59e0b" if dim.status == "WARNING" else "#ef4444")
            dim_rows_html.append(f"""
            <div style="margin-bottom: 14px;">
              <div style="display: flex; justify-content: space-between; font-weight: 600; margin-bottom: 4px; font-size: 13px;">
                <span>{name}</span>
                <span style="color: {color};">{dim.score:.1f}% ({dim.status})</span>
              </div>
              <div style="background: #e2e8f0; height: 8px; border-radius: 4px; overflow: hidden;">
                <div style="background: {color}; width: {dim.score}%; height: 100%;"></div>
              </div>
              <div style="font-size: 11px; color: #64748b; margin-top: 2px;">{dim.summary}</div>
            </div>
            """)

        dim_html_joined = "".join(dim_rows_html)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Data Governance Audit Dashboard - {scorecard.source_info}</title>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      background: #0f172a;
      color: #f8fafc;
      margin: 0;
      padding: 30px;
    }}
    .container {{
      max-width: 900px;
      margin: 0 auto;
      background: #1e293b;
      border-radius: 12px;
      padding: 32px;
      box-shadow: 0 10px 25px rgba(0,0,0,0.3);
      border: 1px solid #334155;
    }}
    .header {{
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid #334155;
      padding-bottom: 20px;
      margin-bottom: 24px;
    }}
    .score-circle {{
      width: 100px;
      height: 100px;
      border-radius: 50%;
      border: 4px solid {status_color};
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      font-weight: 700;
    }}
    .card {{
      background: #0f172a;
      border: 1px solid #334155;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 20px;
    }}
    h1 {{ margin: 0; font-size: 24px; }}
    h2 {{ font-size: 16px; margin-top: 0; border-bottom: 1px solid #334155; padding-bottom: 8px; color: #93c5fd; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div>
        <h1>Data Governance & Quality Audit</h1>
        <p style="color: #94a3b8; margin: 4px 0 0 0; font-size: 13px;">Target: <code>{scorecard.source_info}</code> | Records: {scorecard.total_records:,} | Dimensions: 6</p>
      </div>
      <div class="score-circle">
        <span style="font-size: 24px; color: {status_color};">{score:.0f}</span>
        <span style="font-size: 10px; color: #94a3b8;">/ 100 DAMA</span>
      </div>
    </div>

    <div class="card">
      <h2>DAMA-DMBOK 6 Core Quality Dimensions</h2>
      {dim_html_joined}
    </div>

    <div class="card">
      <h2>Privacy & PII Exposure Risk Assessment</h2>
      <p style="font-weight: 600; color: {'#10b981' if not pii.has_pii_risk else '#ef4444'};">
        Risk Level: {pii.risk_level} ({pii.total_findings} findings)
      </p>
      <p style="font-size: 12px; color: #94a3b8;">
        {'Zero unmasked confidential records detected.' if not pii.has_pii_risk else 'Sensitive tokens or headers flagged. Automated differential privacy masking required prior to LLM injection.'}
      </p>
    </div>

    <div style="text-align: center; font-size: 11px; color: #64748b; margin-top: 24px;">
      Generated by <strong>data-governance-mcp</strong> &bull; DAMA-DMBOK Compliant &bull; <a href="https://github.com/ioseba/data-governance-mcp" style="color: #60a5fa; text-decoration: none;">GitHub Repository</a>
    </div>
  </div>
</body>
</html>"""
        return html
